### ISSUE TITLE
Pro layout 支持多页签么？？

### ISSUE THREAD

**Issue by wkylin** [epeejs/react-components#7]
pro-layout 想要支持多页签如何实现？

**Comment by dobble11** [comment]
![image](https://user-images.githubusercontent.com/23068345/143214408-5ade5105-8c1f-4595-b1db-a7fecca54fb3.png)
这种吗

**Comment by dobble11** [comment]
pro-layout 只关心路由配置的展开，至于如何展示由父组件（布局组件）控制，应该没有什么限制你的场景
